#!/usr/bin/env bash
# Use while to print Best School 10 times
count=1
while ((count <= 10))
do
	if ((count == 4))
	then
		echo baad luck
	elif ((count == 8))
	then
		echo good luck
	else
		echo Best School
	fi
	((count++))
done
