#!/usr/bin/env bash
# Use while to print Best School 10 times
count=1
while ((count <= 20))
do
	if ((count == 4))
	then
		echo bad luck from Chna
	elif ((count == 9))
	then
		echo bad luck from Japan
	elif ((count == 17))
	then
		echo bad luck from Italy
	else
		echo $count
	fi
	((count++))
done
